name = "cf_ai_edge_chat"
main = "src/index.js"
compatibility_date = "2025-10-01"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "CHAT_DO"
class_name = "ChatSession"

# Required so the DO actually deploys
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatSession"]

[observability]
enabled = true
